//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessLib.Data.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MergeGame {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MergeGame() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessLib.Data.Tests.MergeGame", typeof(MergeGame).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 e5 *.
        /// </summary>
        internal static string Simple01Expected {
            get {
                return ResourceManager.GetString("Simple01Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 e5 *.
        /// </summary>
        internal static string Simple01From {
            get {
                return ResourceManager.GetString("Simple01From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 *.
        /// </summary>
        internal static string Simple01To {
            get {
                return ResourceManager.GetString("Simple01To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 e5 2.Nc3 
        ///    ( 2.g3 )
        ///*.
        /// </summary>
        internal static string SimpleVariationExpected01 {
            get {
                return ResourceManager.GetString("SimpleVariationExpected01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 e5 2.g3 ( 2.Nc3 ) 
        ///*
        ///
        ///.
        /// </summary>
        internal static string SimpleVariationExpectedRev01 {
            get {
                return ResourceManager.GetString("SimpleVariationExpectedRev01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 e5 2.g3 *.
        /// </summary>
        internal static string SimpleVariationFrom01 {
            get {
                return ResourceManager.GetString("SimpleVariationFrom01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 e5 2.Nc3 *.
        /// </summary>
        internal static string SimpleVariationTo01 {
            get {
                return ResourceManager.GetString("SimpleVariationTo01", resourceCulture);
            }
        }
    }
}
