//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessLib.Data.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PGN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PGN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessLib.Data.Tests.PGN", typeof(PGN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;Oklahoma City Open&quot;]
        ///[Site &quot;Oklahoma City open&quot;]
        ///[Date &quot;1956.??.??&quot;]
        ///[Round &quot;1&quot;]
        ///[White &quot;Fischer, R.&quot;]
        ///[Black &quot;Popovych, Orest&quot;]
        ///[Result &quot;1-0&quot;]
        ///[ECO &quot;A05&quot;]
        ///
        ///1.Nf3 Nf6 2.g3 g6 3.Bg2 Bg7 4.O-O O-O 5.d3 d6 6.Nbd2 e5 7.e4 Ne8 8.c3 f5 9.d4 f4 10.dxe5 dxe5 11.Nc4 Qxd1 12.Rxd1 Nc6 13.gxf4 exf4 14.Nd4 Nxd4 15.cxd4 f3 16.Bf1 Nf6 17.Ne5 Be6 18.d5 Ng4 19.Nd3 Bc8 20.Bf4 Rxf4 21.Nxf4 Be5 22.Nd3 Bxh2+ 23.Kh1 Bd6 24.Bh3 Ne5 25.Nxe5 Bxe5 26.Be6+ Kg7 27.Rd3 Bxe6 28.dxe6 Kf6 29.Rad1 Re8 30.Rxf3+ Kxe6 31.Kg2  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fischer01 {
            get {
                return ResourceManager.GetString("Fischer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot; White to move.&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;1998.??.??&quot;]
        ///[Round &quot;001&quot;]
        ///[White &quot;Chapter 1&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;1-0&quot;]
        ///[EventDate &quot;1998.??.??&quot;]
        ///[Annotator &quot;Magne,Alf&quot;]
        ///[PlyCount &quot;7&quot;]
        ///[SetUp &quot;1&quot;]
        ///[FEN &quot;r1b2rk1/pp1p1pp1/1b1p2B1/n1qQ2p1/8/5N2/P3RPPP/4R1K1 w - - 0 1&quot;]
        ///
        ///1.Qxf7+ 
        ///    ( 1.Bxf7+ Kh8 
        ///        ( 1...Kh7 2.Qd3+ Kh8 
        ///            ( 2...Qf5 3.Qxf5+ )
        ///        3.Qg6 )
        ///    2.Qd3 )
        ///1...Rxf7 2.Re8+ Rf8 3.Rxf8+ Kxf8 4.Re8# 1-0.
        /// </summary>
        internal static string Puzzle {
            get {
                return ResourceManager.GetString("Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 Nf6 
        ///    ( 1...d5 )
        ///*.
        /// </summary>
        internal static string ShortVariation {
            get {
                return ResourceManager.GetString("ShortVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 Nf6 
        ///    ( 1...e5 )
        ///    ( 1...e6 )
        ///    ( 1...c5 )
        ///2.Nc3 *.
        /// </summary>
        internal static string WithVariations {
            get {
                return ResourceManager.GetString("WithVariations", resourceCulture);
            }
        }
    }
}
