//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessLib.Parse.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PGNResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PGNResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessLib.Parse.Tests.PGNResources", typeof(PGNResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;6. Soviet Team Cup&quot;]
        ///[Site &quot;Riga LAT&quot;]
        ///[Date &quot;1968.12.14&quot;]
        ///[Round &quot;4&quot;]
        ///[White &quot;Hermlin, Aarne&quot;]
        ///[Black &quot;Tal, Mikhail&quot;]
        ///[Result &quot;0-1&quot;]
        ///[ECO &quot;A43w&quot;]
        ///[PlyCount &quot;50&quot;]
        ///
        ///
        ///	   1.	d4 	Nf6 
        ///	   2.	Nf3 	c5 
        ///	   3.	d5 	g6 
        ///	   4.	Nc3 	Bg7 
        ///	   5.	e4 	d6 
        ///	   6.	Bb5+ 	Nbd7 
        ///	   7.	a4 	O-O 
        ///	   8.	O-O 	a6 
        ///	   9.	Be2 	Qc7 
        ///	  10.	h3 	b6 
        ///	  11.	Bf4 	Bb7 
        ///	  12.	Nd2 	e5 
        ///	  13.	dxe6 	fxe6 
        ///	  14.	Nc4 	Nxe4 
        ///	  15.	Bxd6 	Nxd6 
        ///	  16.	Nxd6 	Bc6 
        ///	  17.	Bc4 	Bd4 
        ///	  18.	Bxe6+ 	Kg7 
        ///	  19 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ColumnStyle {
            get {
                return ResourceManager.GetString("ColumnStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;3rd Vergani Cup 2019&quot;]
        ///[Site &quot;Villorba ITA&quot;]
        ///[Date &quot;2019.01.03&quot;]
        ///[Round &quot;4.6&quot;]
        ///[White &quot;Blohberger, Felix&quot;]
        ///[Black &quot;Ter Sahakyan, S&quot;]
        ///[Result &quot;0-1&quot;]
        ///[WhiteElo &quot;2450&quot;]
        ///[BlackElo &quot;2574&quot;]
        ///[ECO &quot;A28&quot;]
        ///
        ///1.c4 e5 2.Nc3 Nf6 3.Nf3 Nc6 4.e3 Bb4 5.Qc2 O-O 6.Nd5 Re8 7.Ng5 g6 8.h4 Bf8
        ///9.Nxf6+ Qxf6 10.Be2 Qe7 11.g4 e4 12.b3 d5 13.cxd5 Nb4 14.Qc4 b5 15.d6 Qf6 
        ///16.Bb2 bxc4 17.Bxf6 h6 18.Bxc4 hxg5 19.hxg5 Bg7 20.O-O-O Bxg4 21.Rdg1 Bf3 
        ///22.Rh6 Bxh6 23.gxh6 Nd3+ 24.Kc2 Ne5 25.d7 Nxd7 26.Rxg6+ Kh7 27.Rg7+  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EnglishRevSic {
            get {
                return ResourceManager.GetString("EnglishRevSic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 e5 2.g3 Nf6 3.Nc3 *.
        /// </summary>
        public static string FilterOut {
            get {
                return ResourceManager.GetString("FilterOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 e5.
        /// </summary>
        public static string FilterTooShort {
            get {
                return ResourceManager.GetString("FilterTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;New York&quot;]
        ///[Site &quot;New York, NY USA&quot;]
        ///[Date &quot;1857.??.??&quot;]
        ///[Round &quot;1&quot;]
        ///[White &quot;Morphy, Paul&quot;]
        ///[Black &quot;Meek, Alexander Beaufort&quot;]
        ///[Result &quot;1-0&quot;]
        ///[ECO &quot;A43g&quot;]
        ///
        ///
        ///	   1.	e4          	e6          
        ///	   2.	d4          	c5          
        ///	   3.	d5          	e5          
        ///	   4.	f4          	d6          
        ///	   5.	Nf3         	Bg4         
        ///	   6.	fxe5        	Bxf3        
        ///	   7.	Qxf3        	dxe5        
        ///	   8.	Bb5+        	Nd7         
        ///	   9.	Nc3         	Nf6         
        ///	  10.	Bg5         	Be7         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FiveGames {
            get {
                return ResourceManager.GetString("FiveGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;exhibition&quot;]
        ///[Site &quot;exhibition&quot;]
        ///[Date &quot;1949.??.??&quot;]
        ///[Round &quot;1&quot;]
        ///[White &quot;Tal, Mikhail&quot;]
        ///[Black &quot;Gulko, Boris F&quot;]
        ///[Result &quot;1-0&quot;]
        ///[ECO &quot;B82&quot;]
        ///
        ///1. e4 c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. Nc3 e6 6. f4 Nc6 7. Be3 Be7 8. Qf3
        ///a6 $1 9. O-O-O Qc7 { Qc7 is a great move, here.}  10. g4 Nxd4 11. Bxd4 e5 12.
        ///fxe5 dxe5 13. Qg3 Nxg4 14. Be2 Qa5 15. Bxg4 exd4 16. Nd5 Qxa2 17. Qe5 Qa1+ 18.
        ///Kd2 Qa5+ 19. b4 Qd8 20. Rhg1 f6 21. Bh5+ Kf8 22. Rxg7 fxe5 23. Rf7+ Ke8 24.
        ///Rxe7+ Kf8 25. Rf1+ Kg8 26. Rff7  1-0.
        /// </summary>
        public static string GameWithNAG {
            get {
                return ResourceManager.GetString("GameWithNAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. e4 c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. Nc3 a6 6. f4 e5 7. Nf3 Nbd7 8. Bd3
        ///Be7 9. O-O O-O 10. Kh1 b5 11. a3 Qc7 12. fxe5 dxe5 13. Nh4 Nc5 14. Bg5 Qd8 15.
        ///Nf5 Bxf5 16. Rxf5 Nfd7 17. Bxe7 Qxe7 18. Nd5 Qd6 19. Qg4 g6 20. Raf1 f6 21. h4
        ///Kh8 22. R5f3 f5 23. exf5 Qxd5 24. fxg6 Rxf3 25. g7+ Kg8 26. Bxh7+ Kxh7 27. Rxf3
        ///Ne4 28. h5 Ndf6 29. Qg6+ Kg8 30. h6 Ra7 31. Kh2 Re7 32. Rh3 Nh7 33. Rd3 Qa8 34.
        ///Qxe4 Qxe4 35. Rd8+ Kf7 36. g8=Q+ Kf6 37. Rd6+ Kf5 38. Qg6+ Kf4 39. g3+ Ke3 40.
        ///Rd3+ Qxd3  1-0.
        /// </summary>
        public static string GameWithPromotion {
            get {
                return ResourceManager.GetString("GameWithPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;exhibition&quot;]
        ///[Site &quot;exhibition&quot;]
        ///[Date &quot;1949.??.??&quot;]
        ///[Round &quot;1&quot;]
        ///[White &quot;Tal, Mikhail&quot;]
        ///[Black &quot;Gulko, Boris F&quot;]
        ///[Result &quot;1-0&quot;]
        ///[ECO &quot;B82&quot;]
        ///
        ///1. e4 ( 1. c4)1... c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. Nc3 e6 6. f4 Nc6 7.
        ///Be3 Be7 8. Qf3 a6 $1 9. O-O-O Qc7 { Qc7 is a great move, here.}  10. g4 Nxd4
        ///11. Bxd4 e5 12. fxe5 dxe5 13. Qg3 Nxg4 14. Be2 Qa5 15. Bxg4 exd4 16. Nd5 Qxa2
        ///17. Qe5 Qa1+ 18. Kd2 Qa5+ 19. b4 Qd8 20. Rhg1 f6 21. Bh5+ Kf8 22. Rxg7 fxe5 23.
        ///Rf7+ Ke8 24. Rxe7+ Kf8 25. Rf1+ Kg8 2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GameWithVariation {
            get {
                return ResourceManager.GetString("GameWithVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;2019 US Open&quot;]
        ///[Site &quot;Orlando, FL USA&quot;]
        ///[Date &quot;2019.08.03&quot;]
        ///[Round &quot;1&quot;]
        ///[White &quot;Biernacki, Mark&quot;]
        ///[Black &quot;Yan, Henry&quot;]
        ///[Result &quot;1-0&quot;]
        ///[WhiteElo &quot;2159&quot;]
        ///[BlackElo &quot;1650&quot;]
        ///[ECO &quot;A00v&quot;]
        ///[EventDate &quot;2019.08.04&quot;]
        ///[UTCDate &quot;2019.08.04&quot;]
        ///[UTCTime &quot;16:33:57&quot;]
        ///[Variant &quot;Standard&quot;]
        ///[Opening &quot;Hungarian Opening: Indian Defense&quot;]
        ///[Annotator &quot;https://lichess.org/@/liquormark&quot;]
        ///
        ///1.g3 Nf6 2.Bg2 d5 3.Na3 
        ///    {Obviously a bad move, but wanted to make the game interesting.}
        ///3...Bf5 
        ///    ( 3...e5 4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GameWithVars {
            get {
                return ResourceManager.GetString("GameWithVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] medium {
            get {
                object obj = ResourceManager.GetObject("medium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1. c4 e5 2. Nc3 $3 *.
        /// </summary>
        public static string MoveNagNumber {
            get {
                return ResourceManager.GetString("MoveNagNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1. c4 e5 2. Nc3!! *.
        /// </summary>
        public static string MoveNagSymbol {
            get {
                return ResourceManager.GetString("MoveNagSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;Riga Junior Ch Semi-final&quot;]
        ///[Site &quot;Riga LAT&quot;]
        ///[Date &quot;1949.??.??&quot;]
        ///[Round &quot;1&quot;]
        ///[White &quot;Tal, Mikhail&quot;]
        ///[Black &quot;Leonov&quot;]
        ///[Result &quot;1-0&quot;]
        ///[ECO &quot;B13e&quot;]
        ///
        ///{In book The Life and Games of Mikhail Tal} 
        ///1.e4 
        ///    {A great move.}
        ///1...c6 2.d4 d5 3.exd5 cxd5 4.Bd3 Nf6 5.h3 h6 $6 
        ///    {Unnecessary here.}
        ///6.Bf4 e6 7.Nf3 Bd6 8.Bxd6 Qxd6 9.c3 Nc6 10.O-O O-O 11.Qe2 Re8 12.Ne5 Qc7 13.f4 Nxe5 $4 14.fxe5 Nh7 15.Qh5 Re7 16.Na3 $6 a6 17.Nc2 
        ///    {wasted move}
        ///17...Qd7 18.Ne3 Qe8 19.Rf6 $1 
        ///    {&quot;A blockadi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PregameComment {
            get {
                return ResourceManager.GetString("PregameComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;London&quot;]
        ///[Site &quot;London ENG&quot;]
        ///[Date &quot;1826.??.??&quot;]
        ///[Round &quot;1&quot;]
        ///[White &quot;Evans, William&quot;]
        ///[Black &quot;MacDonnell, Alexander&quot;]
        ///[Result &quot;1-0&quot;]
        ///[ECO &quot;C52&quot;]
        ///
        ///1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5 4.O-O d6 5.b4 Bxb4 6.c3 Ba5 7.d4 Bg4 8.Qb3 Qd7 9.Ng5 Nd8 10.dxe5 dxe5 11.Ba3 Nh6 12.f3 Bb6+ 13.Kh1 Bh5 14.Rd1 Qc8 15.Rxd8+ Qxd8 16.Nxf7 Qh4 17.Qb5+ c6 18.Qxe5+ Kd7 19.Qe6+ Kc7 20.Bd6# 1-0.
        /// </summary>
        public static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] small {
            get {
                object obj = ResourceManager.GetObject("small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;] [Site &quot;?&quot;] [Date &quot;????.??.??&quot;] [Round &quot;?&quot;] [White &quot;?&quot;] [Black &quot;?&quot;] [Result &quot;*&quot;] 1.c4 Nf6 ( 1...e5 ) ( 1...e6 ) ( 1...c5 ) 2.Nc3 *.
        /// </summary>
        public static string smallPgn {
            get {
                return ResourceManager.GetString("smallPgn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] tal {
            get {
                object obj = ResourceManager.GetObject("tal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] talLarge {
            get {
                object obj = ResourceManager.GetObject("talLarge", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] talMedium {
            get {
                object obj = ResourceManager.GetObject("talMedium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] tiny {
            get {
                object obj = ResourceManager.GetObject("tiny", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 Nf6 2.Nc3 Ng8 3.Nb1 e5 4.Nc3 *.
        /// </summary>
        public static string TranspositionToFilter {
            get {
                return ResourceManager.GetString("TranspositionToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;2. Soviet Team Cup&quot;]
        ///[Site &quot;Riga URS&quot;]
        ///[Date &quot;1954.09.04&quot;]
        ///[Round &quot;1&quot;]
        ///[White &quot;Tal, Mikhail&quot;]
        ///[Black &quot;Averbakh, Yuri L&quot;]
        ///[Result &quot;1-0&quot;]
        ///[ECO &quot;C47&quot;]
        ///[PlyCount &quot;80&quot;]
        ///
        ///1. e4 e5 2. Nf3 Nc6 3. Nc3 Nf6 4. d4 exd4 5. Nd5 Nb4 6. Nxd4 Nxe4 7. Nf5 c6 (
        ///7... Nxd5)8. Nxb4 Bxb4+ 9. c3 Qf6 10. Qf3 Nxc3 11. a3 Ba5 12. Bd2 d5 13. Ng3
        ///Qe6+ 14. Qe3 d4 15. Qxe6+ Bxe6 16. f3 O-O-O 17. Kf2 Bb6 18. bxc3 dxc3+ 19. Be3
        ///Bxe3+ 20. Kxe3 Rhe8 21. Ne4 Bd5 ( 21... Bb3 22. g4 $10 )22. g4 $1 { preventing
        ///...f5}  ( 22 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Variation02 {
            get {
                return ResourceManager.GetString("Variation02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;FIDE (23) 1958-1960&quot;]
        ///[Site &quot;Portoroz izt&quot;]
        ///[Date &quot;1958.??.??&quot;]
        ///[Round &quot;17&quot;]
        ///[White &quot;Tal, Mikhail&quot;]
        ///[Black &quot;Panno, Oscar&quot;]
        ///[Result &quot;1-0&quot;]
        ///[ECO &quot;C92e&quot;]
        ///
        ///1.e4 e5 2.Nf3 Nc6 3.Bb5 a6 4.Ba4 Nf6 5.O-O Be7 6.Re1 b5 7.Bb3 d6 8.c3 O-O 
        ///9.h3 Nd7 {A popular variation at that time -Kasparov} 10.d4 Nb6 ( 10...Bf6
        ///11.a4 $14 ( 11.Be3 $2 Na5 12.Bc2 Nc4 $10 {Spassky-Petrosian, Moscow 21st 
        ///matchgame 1969} ) ) 11.Be3 {Fashionable at the time. } ( {&quot;A harmless 
        ///alternative is...&quot;
        ///--Kasparov} 11.dxe5 Nxe5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VariationsAndComments {
            get {
                return ResourceManager.GetString("VariationsAndComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot; White to move.&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;1998.??.??&quot;]
        ///[Round &quot;029&quot;]
        ///[White &quot;Chapter 1&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;1-0&quot;]
        ///[Annotator &quot;Magne,Alf&quot;]
        ///[EventDate &quot;1998.??.??&quot;]
        ///[FEN &quot;2qrr1n1/3b1kp1/2pBpn1p/1p2PP2/p2P4/1BP5/P3Q1PP/4RRK1 w - - 0 1&quot;]
        ///[PlyCount &quot;19&quot;]
        ///[SetUp &quot;1&quot;]
        ///
        ///1. Qh5+ Nxh5 2. fxe6+ Kg6 3. Bc2+ Kg5 4. Rf5+ Kg6 5. Rf6+ Kg5 6. Rg6+ Kh4 ( 6...
        ///Kf4 7. Re4+ Kf5 8. Rh4# )7. Re4+ Nf4 8. Rxf4+ Kh5 9. Rg3 g5 10. Rh3#  1-0.
        /// </summary>
        public static string WithFENSetup {
            get {
                return ResourceManager.GetString("WithFENSetup", resourceCulture);
            }
        }
    }
}
