//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessLib.Parse.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PGNResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PGNResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessLib.Parse.Tests.PGNResources", typeof(PGNResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;6. Soviet Team Cup&quot;]
        ///[Site &quot;Riga LAT&quot;]
        ///[Date &quot;1968.12.14&quot;]
        ///[Round &quot;4&quot;]
        ///[White &quot;Hermlin, Aarne&quot;]
        ///[Black &quot;Tal, Mikhail&quot;]
        ///[Result &quot;0-1&quot;]
        ///[ECO &quot;A43w&quot;]
        ///[PlyCount &quot;50&quot;]
        ///
        ///
        ///	   1.	d4 	Nf6 
        ///	   2.	Nf3 	c5 
        ///	   3.	d5 	g6 
        ///	   4.	Nc3 	Bg7 
        ///	   5.	e4 	d6 
        ///	   6.	Bb5+ 	Nbd7 
        ///	   7.	a4 	O-O 
        ///	   8.	O-O 	a6 
        ///	   9.	Be2 	Qc7 
        ///	  10.	h3 	b6 
        ///	  11.	Bf4 	Bb7 
        ///	  12.	Nd2 	e5 
        ///	  13.	dxe6 	fxe6 
        ///	  14.	Nc4 	Nxe4 
        ///	  15.	Bxd6 	Nxd6 
        ///	  16.	Nxd6 	Bc6 
        ///	  17.	Bc4 	Bd4 
        ///	  18.	Bxe6+ 	Kg7 
        ///	  19 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ColumnStyle {
            get {
                return ResourceManager.GetString("ColumnStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;exhibition&quot;]
        ///[Site &quot;exhibition&quot;]
        ///[Date &quot;1949.??.??&quot;]
        ///[Round &quot;1&quot;]
        ///[White &quot;Tal, Mikhail&quot;]
        ///[Black &quot;Gulko, Boris F&quot;]
        ///[Result &quot;1-0&quot;]
        ///[ECO &quot;B82&quot;]
        ///
        ///1. e4 c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. Nc3 e6 6. f4 Nc6 7. Be3 Be7 8. Qf3
        ///a6 $1 9. O-O-O Qc7 { Qc7 is a great move, here.}  10. g4 Nxd4 11. Bxd4 e5 12.
        ///fxe5 dxe5 13. Qg3 Nxg4 14. Be2 Qa5 15. Bxg4 exd4 16. Nd5 Qxa2 17. Qe5 Qa1+ 18.
        ///Kd2 Qa5+ 19. b4 Qd8 20. Rhg1 f6 21. Bh5+ Kf8 22. Rxg7 fxe5 23. Rf7+ Ke8 24.
        ///Rxe7+ Kf8 25. Rf1+ Kg8 26. Rff7  1-0.
        /// </summary>
        internal static string GameWithNAG {
            get {
                return ResourceManager.GetString("GameWithNAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;exhibition&quot;]
        ///[Site &quot;exhibition&quot;]
        ///[Date &quot;1949.??.??&quot;]
        ///[Round &quot;1&quot;]
        ///[White &quot;Tal, Mikhail&quot;]
        ///[Black &quot;Gulko, Boris F&quot;]
        ///[Result &quot;1-0&quot;]
        ///[ECO &quot;B82&quot;]
        ///
        ///1. e4 ( 1. c4)1... c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. Nc3 e6 6. f4 Nc6 7.
        ///Be3 Be7 8. Qf3 a6 $1 9. O-O-O Qc7 { Qc7 is a great move, here.}  10. g4 Nxd4
        ///11. Bxd4 e5 12. fxe5 dxe5 13. Qg3 Nxg4 14. Be2 Qa5 15. Bxg4 exd4 16. Nd5 Qxa2
        ///17. Qe5 Qa1+ 18. Kd2 Qa5+ 19. b4 Qd8 20. Rhg1 f6 21. Bh5+ Kf8 22. Rxg7 fxe5 23.
        ///Rf7+ Ke8 24. Rxe7+ Kf8 25. Rf1+ Kg8 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameWithVariation {
            get {
                return ResourceManager.GetString("GameWithVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;2019 US Open&quot;]
        ///[Site &quot;Orlando, FL USA&quot;]
        ///[Date &quot;2019.08.03&quot;]
        ///[Round &quot;1&quot;]
        ///[White &quot;Biernacki, Mark&quot;]
        ///[Black &quot;Yan, Henry&quot;]
        ///[Result &quot;1-0&quot;]
        ///[WhiteElo &quot;2159&quot;]
        ///[BlackElo &quot;1650&quot;]
        ///[ECO &quot;A00v&quot;]
        ///[EventDate &quot;2019.08.04&quot;]
        ///[UTCDate &quot;2019.08.04&quot;]
        ///[UTCTime &quot;16:33:57&quot;]
        ///[Variant &quot;Standard&quot;]
        ///[Opening &quot;Hungarian Opening: Indian Defense&quot;]
        ///[Annotator &quot;https://lichess.org/@/liquormark&quot;]
        ///
        ///1.g3 Nf6 2.Bg2 d5 3.Na3 
        ///    {Obviously a bad move, but wanted to make the game interesting.}
        ///3...Bf5 
        ///    ( 3...e5 4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameWithVars {
            get {
                return ResourceManager.GetString("GameWithVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;London&quot;]
        ///[Site &quot;London ENG&quot;]
        ///[Date &quot;1826.??.??&quot;]
        ///[Round &quot;1&quot;]
        ///[White &quot;Evans, William&quot;]
        ///[Black &quot;MacDonnell, Alexander&quot;]
        ///[Result &quot;1-0&quot;]
        ///[ECO &quot;C52&quot;]
        ///
        ///1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5 4.O-O d6 5.b4 Bxb4 6.c3 Ba5 7.d4 Bg4 8.Qb3 Qd7 9.Ng5 Nd8 10.dxe5 dxe5 11.Ba3 Nh6 12.f3 Bb6+ 13.Kh1 Bh5 14.Rd1 Qc8 15.Rxd8+ Qxd8 16.Nxf7 Qh4 17.Qb5+ c6 18.Qxe5+ Kd7 19.Qe6+ Kc7 20.Bd6# 1-0.
        /// </summary>
        internal static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] talLarge {
            get {
                object obj = ResourceManager.GetObject("talLarge", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
