//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\PGN.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ChessLib.Parse.Parser.Base {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class PGNLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		WHITE_WINS=1, BLACK_WINS=2, DRAWN_GAME=3, BOL=4, REST_OF_LINE_COMMENT=5, 
		BRACE_COMMENT=6, ESCAPE=7, NEW_LINE=8, SPACES=9, STRING=10, INTEGER=11, 
		PERIOD=12, ASTERISK=13, LEFT_BRACKET=14, RIGHT_BRACKET=15, LEFT_PARENTHESIS=16, 
		RIGHT_PARENTHESIS=17, LEFT_ANGLE_BRACKET=18, RIGHT_ANGLE_BRACKET=19, NUMERIC_ANNOTATION_GLYPH=20, 
		SYMBOL=21, SUFFIX_ANNOTATION=22, UNEXPECTED_CHAR=23;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"WHITE_WINS", "BLACK_WINS", "DRAWN_GAME", "BOL", "REST_OF_LINE_COMMENT", 
		"BRACE_COMMENT", "ESCAPE", "NEW_LINE", "SPACES", "STRING", "INTEGER", 
		"PERIOD", "ASTERISK", "LEFT_BRACKET", "RIGHT_BRACKET", "LEFT_PARENTHESIS", 
		"RIGHT_PARENTHESIS", "LEFT_ANGLE_BRACKET", "RIGHT_ANGLE_BRACKET", "NUMERIC_ANNOTATION_GLYPH", 
		"SYMBOL", "SUFFIX_ANNOTATION", "UNEXPECTED_CHAR"
	};


	public PGNLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public PGNLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'1-0'", "'0-1'", "'1/2-1/2'", null, null, null, null, null, null, 
		null, null, "'.'", "'*'", "'['", "']'", "'('", "')'", "'<'", "'>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "WHITE_WINS", "BLACK_WINS", "DRAWN_GAME", "BOL", "REST_OF_LINE_COMMENT", 
		"BRACE_COMMENT", "ESCAPE", "NEW_LINE", "SPACES", "STRING", "INTEGER", 
		"PERIOD", "ASTERISK", "LEFT_BRACKET", "RIGHT_BRACKET", "LEFT_PARENTHESIS", 
		"RIGHT_PARENTHESIS", "LEFT_ANGLE_BRACKET", "RIGHT_ANGLE_BRACKET", "NUMERIC_ANNOTATION_GLYPH", 
		"SYMBOL", "SUFFIX_ANNOTATION", "UNEXPECTED_CHAR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PGN.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static PGNLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x19', '\xA7', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x6', '\x5', '\x43', '\n', '\x5', 
		'\r', '\x5', '\xE', '\x5', '\x44', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', 
		'I', '\n', '\x6', '\f', '\x6', '\xE', '\x6', 'L', '\v', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\a', '\a', 'R', '\n', 
		'\a', '\f', '\a', '\xE', '\a', 'U', '\v', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\b', '\x5', '\b', '\\', '\n', '\b', 
		'\x3', '\b', '\x3', '\b', '\a', '\b', '`', '\n', '\b', '\f', '\b', '\xE', 
		'\b', '\x63', '\v', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x5', 
		'\t', 'h', '\n', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x6', '\n', 
		'm', '\n', '\n', '\r', '\n', '\xE', '\n', 'n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\a', '\v', 'y', '\n', '\v', '\f', '\v', '\xE', '\v', '|', '\v', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x6', '\f', '\x81', '\n', 
		'\f', '\r', '\f', '\xE', '\f', '\x82', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', 
		'\x15', '\x6', '\x15', '\x97', '\n', '\x15', '\r', '\x15', '\xE', '\x15', 
		'\x98', '\x3', '\x16', '\x3', '\x16', '\a', '\x16', '\x9D', '\n', '\x16', 
		'\f', '\x16', '\xE', '\x16', '\xA0', '\v', '\x16', '\x3', '\x17', '\x3', 
		'\x17', '\x5', '\x17', '\xA4', '\n', '\x17', '\x3', '\x18', '\x3', '\x18', 
		'\x2', '\x2', '\x19', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', 
		'\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', 
		'\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', 
		'\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', 
		'+', '\x17', '-', '\x18', '/', '\x19', '\x3', '\x2', '\v', '\x4', '\x2', 
		'\f', '\f', '\xE', '\xF', '\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x3', 
		'\x2', '\x7F', '\x7F', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', 
		'\x4', '\x2', '$', '$', '^', '^', '\x3', '\x2', '\x32', ';', '\x5', '\x2', 
		'\x32', ';', '\x43', '\\', '\x63', '|', '\n', '\x2', '%', '%', '-', '-', 
		'/', '/', '\x32', '<', '?', '?', '\x43', '\\', '\x61', '\x61', '\x63', 
		'|', '\x4', '\x2', '#', '#', '\x41', '\x41', '\x2', '\xB4', '\x2', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x3', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\x5', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\a', '\x39', '\x3', '\x2', '\x2', '\x2', '\t', '\x42', '\x3', 
		'\x2', '\x2', '\x2', '\v', '\x46', '\x3', '\x2', '\x2', '\x2', '\r', 'O', 
		'\x3', '\x2', '\x2', '\x2', '\xF', '[', '\x3', '\x2', '\x2', '\x2', '\x11', 
		'g', '\x3', '\x2', '\x2', '\x2', '\x13', 'l', '\x3', '\x2', '\x2', '\x2', 
		'\x15', 'r', '\x3', '\x2', '\x2', '\x2', '\x17', '\x80', '\x3', '\x2', 
		'\x2', '\x2', '\x19', '\x84', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x86', 
		'\x3', '\x2', '\x2', '\x2', '\x1D', '\x88', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', '\x8A', '\x3', '\x2', '\x2', '\x2', '!', '\x8C', '\x3', '\x2', 
		'\x2', '\x2', '#', '\x8E', '\x3', '\x2', '\x2', '\x2', '%', '\x90', '\x3', 
		'\x2', '\x2', '\x2', '\'', '\x92', '\x3', '\x2', '\x2', '\x2', ')', '\x94', 
		'\x3', '\x2', '\x2', '\x2', '+', '\x9A', '\x3', '\x2', '\x2', '\x2', '-', 
		'\xA1', '\x3', '\x2', '\x2', '\x2', '/', '\xA5', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '\x32', '\a', '\x33', '\x2', '\x2', '\x32', '\x33', '\a', 
		'/', '\x2', '\x2', '\x33', '\x34', '\a', '\x32', '\x2', '\x2', '\x34', 
		'\x4', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', '\x32', '\x2', 
		'\x2', '\x36', '\x37', '\a', '/', '\x2', '\x2', '\x37', '\x38', '\a', 
		'\x33', '\x2', '\x2', '\x38', '\x6', '\x3', '\x2', '\x2', '\x2', '\x39', 
		':', '\a', '\x33', '\x2', '\x2', ':', ';', '\a', '\x31', '\x2', '\x2', 
		';', '<', '\a', '\x34', '\x2', '\x2', '<', '=', '\a', '/', '\x2', '\x2', 
		'=', '>', '\a', '\x33', '\x2', '\x2', '>', '?', '\a', '\x31', '\x2', '\x2', 
		'?', '@', '\a', '\x34', '\x2', '\x2', '@', '\b', '\x3', '\x2', '\x2', 
		'\x2', '\x41', '\x43', '\t', '\x2', '\x2', '\x2', '\x42', '\x41', '\x3', 
		'\x2', '\x2', '\x2', '\x43', '\x44', '\x3', '\x2', '\x2', '\x2', '\x44', 
		'\x42', '\x3', '\x2', '\x2', '\x2', '\x44', '\x45', '\x3', '\x2', '\x2', 
		'\x2', '\x45', '\n', '\x3', '\x2', '\x2', '\x2', '\x46', 'J', '\a', '=', 
		'\x2', '\x2', 'G', 'I', '\n', '\x3', '\x2', '\x2', 'H', 'G', '\x3', '\x2', 
		'\x2', '\x2', 'I', 'L', '\x3', '\x2', '\x2', '\x2', 'J', 'H', '\x3', '\x2', 
		'\x2', '\x2', 'J', 'K', '\x3', '\x2', '\x2', '\x2', 'K', 'M', '\x3', '\x2', 
		'\x2', '\x2', 'L', 'J', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\b', '\x6', 
		'\x2', '\x2', 'N', '\f', '\x3', '\x2', '\x2', '\x2', 'O', 'S', '\a', '}', 
		'\x2', '\x2', 'P', 'R', '\n', '\x4', '\x2', '\x2', 'Q', 'P', '\x3', '\x2', 
		'\x2', '\x2', 'R', 'U', '\x3', '\x2', '\x2', '\x2', 'S', 'Q', '\x3', '\x2', 
		'\x2', '\x2', 'S', 'T', '\x3', '\x2', '\x2', '\x2', 'T', 'V', '\x3', '\x2', 
		'\x2', '\x2', 'U', 'S', '\x3', '\x2', '\x2', '\x2', 'V', 'W', '\a', '\x7F', 
		'\x2', '\x2', 'W', 'X', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\b', '\a', 
		'\x2', '\x2', 'Y', '\xE', '\x3', '\x2', '\x2', '\x2', 'Z', '\\', '\x5', 
		'\t', '\x5', '\x2', '[', 'Z', '\x3', '\x2', '\x2', '\x2', '[', '\\', '\x3', 
		'\x2', '\x2', '\x2', '\\', ']', '\x3', '\x2', '\x2', '\x2', ']', '\x61', 
		'\a', '\'', '\x2', '\x2', '^', '`', '\n', '\x3', '\x2', '\x2', '_', '^', 
		'\x3', '\x2', '\x2', '\x2', '`', '\x63', '\x3', '\x2', '\x2', '\x2', '\x61', 
		'_', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '\x64', '\x3', '\x2', '\x2', '\x2', '\x63', '\x61', '\x3', 
		'\x2', '\x2', '\x2', '\x64', '\x65', '\b', '\b', '\x2', '\x2', '\x65', 
		'\x10', '\x3', '\x2', '\x2', '\x2', '\x66', 'h', '\a', '\xF', '\x2', '\x2', 
		'g', '\x66', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\x3', '\x2', '\x2', 
		'\x2', 'h', 'i', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\a', '\f', '\x2', 
		'\x2', 'j', '\x12', '\x3', '\x2', '\x2', '\x2', 'k', 'm', '\t', '\x5', 
		'\x2', '\x2', 'l', 'k', '\x3', '\x2', '\x2', '\x2', 'm', 'n', '\x3', '\x2', 
		'\x2', '\x2', 'n', 'l', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\x3', '\x2', 
		'\x2', '\x2', 'o', 'p', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\b', '\n', 
		'\x2', '\x2', 'q', '\x14', '\x3', '\x2', '\x2', '\x2', 'r', 'z', '\a', 
		'$', '\x2', '\x2', 's', 't', '\a', '^', '\x2', '\x2', 't', 'y', '\a', 
		'^', '\x2', '\x2', 'u', 'v', '\a', '^', '\x2', '\x2', 'v', 'y', '\a', 
		'$', '\x2', '\x2', 'w', 'y', '\n', '\x6', '\x2', '\x2', 'x', 's', '\x3', 
		'\x2', '\x2', '\x2', 'x', 'u', '\x3', '\x2', '\x2', '\x2', 'x', 'w', '\x3', 
		'\x2', '\x2', '\x2', 'y', '|', '\x3', '\x2', '\x2', '\x2', 'z', 'x', '\x3', 
		'\x2', '\x2', '\x2', 'z', '{', '\x3', '\x2', '\x2', '\x2', '{', '}', '\x3', 
		'\x2', '\x2', '\x2', '|', 'z', '\x3', '\x2', '\x2', '\x2', '}', '~', '\a', 
		'$', '\x2', '\x2', '~', '\x16', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x81', 
		'\t', '\a', '\x2', '\x2', '\x80', '\x7F', '\x3', '\x2', '\x2', '\x2', 
		'\x81', '\x82', '\x3', '\x2', '\x2', '\x2', '\x82', '\x80', '\x3', '\x2', 
		'\x2', '\x2', '\x82', '\x83', '\x3', '\x2', '\x2', '\x2', '\x83', '\x18', 
		'\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\a', '\x30', '\x2', '\x2', 
		'\x85', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\a', ',', 
		'\x2', '\x2', '\x87', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', 
		'\a', ']', '\x2', '\x2', '\x89', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x8B', '\a', '_', '\x2', '\x2', '\x8B', ' ', '\x3', '\x2', '\x2', '\x2', 
		'\x8C', '\x8D', '\a', '*', '\x2', '\x2', '\x8D', '\"', '\x3', '\x2', '\x2', 
		'\x2', '\x8E', '\x8F', '\a', '+', '\x2', '\x2', '\x8F', '$', '\x3', '\x2', 
		'\x2', '\x2', '\x90', '\x91', '\a', '>', '\x2', '\x2', '\x91', '&', '\x3', 
		'\x2', '\x2', '\x2', '\x92', '\x93', '\a', '@', '\x2', '\x2', '\x93', 
		'(', '\x3', '\x2', '\x2', '\x2', '\x94', '\x96', '\a', '&', '\x2', '\x2', 
		'\x95', '\x97', '\t', '\a', '\x2', '\x2', '\x96', '\x95', '\x3', '\x2', 
		'\x2', '\x2', '\x97', '\x98', '\x3', '\x2', '\x2', '\x2', '\x98', '\x96', 
		'\x3', '\x2', '\x2', '\x2', '\x98', '\x99', '\x3', '\x2', '\x2', '\x2', 
		'\x99', '*', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9E', '\t', '\b', '\x2', 
		'\x2', '\x9B', '\x9D', '\t', '\t', '\x2', '\x2', '\x9C', '\x9B', '\x3', 
		'\x2', '\x2', '\x2', '\x9D', '\xA0', '\x3', '\x2', '\x2', '\x2', '\x9E', 
		'\x9C', '\x3', '\x2', '\x2', '\x2', '\x9E', '\x9F', '\x3', '\x2', '\x2', 
		'\x2', '\x9F', ',', '\x3', '\x2', '\x2', '\x2', '\xA0', '\x9E', '\x3', 
		'\x2', '\x2', '\x2', '\xA1', '\xA3', '\t', '\n', '\x2', '\x2', '\xA2', 
		'\xA4', '\t', '\n', '\x2', '\x2', '\xA3', '\xA2', '\x3', '\x2', '\x2', 
		'\x2', '\xA3', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA4', '.', '\x3', 
		'\x2', '\x2', '\x2', '\xA5', '\xA6', '\v', '\x2', '\x2', '\x2', '\xA6', 
		'\x30', '\x3', '\x2', '\x2', '\x2', '\x10', '\x2', '\x44', 'J', 'S', '[', 
		'\x61', 'g', 'n', 'x', 'z', '\x82', '\x98', '\x9E', '\xA3', '\x3', '\b', 
		'\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace ChessLib.Parse.Parser.Base
