//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessLib.Core.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PGN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PGN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessLib.Core.Tests.PGN", typeof(PGN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;Oklahoma City Open&quot;]
        ///[Site &quot;Oklahoma City open&quot;]
        ///[Date &quot;1956.??.??&quot;]
        ///[Round &quot;1&quot;]
        ///[White &quot;Fischer, R.&quot;]
        ///[Black &quot;Popovych, Orest&quot;]
        ///[Result &quot;1-0&quot;]
        ///[ECO &quot;A05&quot;]
        ///
        ///1.Nf3 Nf6 2.g3 g6 3.Bg2 Bg7 4.O-O O-O 5.d3 d6 6.Nbd2 e5 7.e4 Ne8 8.c3 f5 9.d4 f4 10.dxe5 dxe5 11.Nc4 Qxd1 12.Rxd1 Nc6 13.gxf4 exf4 14.Nd4 Nxd4 15.cxd4 f3 16.Bf1 Nf6 17.Ne5 Be6 18.d5 Ng4 19.Nd3 Bc8 20.Bf4 Rxf4 21.Nxf4 Be5 22.Nd3 Bxh2+ 23.Kh1 Bd6 24.Bh3 Ne5 25.Nxe5 Bxe5 26.Be6+ Kg7 27.Rd3 Bxe6 28.dxe6 Kf6 29.Rad1 Re8 30.Rxf3+ Kxe6 31.Kg2  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fischer01 {
            get {
                return ResourceManager.GetString("Fischer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 Nf6 2.d4 e6.
        /// </summary>
        internal static string g1 {
            get {
                return ResourceManager.GetString("g1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;&quot;]
        ///[Site &quot;&quot;]
        ///[Date &quot;&quot;]
        ///[Round &quot;&quot;]
        ///[White &quot;&quot;]
        ///[Black &quot;&quot;]
        ///[Result &quot;&quot;]
        ///
        ///1. c4 Nf6 2. d4 Nc6.
        /// </summary>
        internal static string g1SplitFromVariation {
            get {
                return ResourceManager.GetString("g1SplitFromVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 Nf6 2.d4 e6 
        ///    ( 2...g6 3.f3 )
        ///    ( 2...Nc6 )
        ///*.
        /// </summary>
        internal static string g1Variation {
            get {
                return ResourceManager.GetString("g1Variation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 Nf6 2.d4 e6 
        ///    ( 2...g6 3.f3 )
        ///*.
        /// </summary>
        internal static string g1VariationNotEqual {
            get {
                return ResourceManager.GetString("g1VariationNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;The Mediocre of Chess&quot;]
        ///[Site &quot;New York City, NY USA&quot;]
        ///[Date &quot;2021.08.18&quot;]
        ///[Round &quot;2&quot;]
        ///[White &quot;GoodPlayer, One&quot;]
        ///[Black &quot;DecentPlayer, A.&quot;]
        ///[Result &quot;1-0&quot;]
        ///[ECO &quot;D51&quot;]
        ///[EventDate &quot;2021.08.16&quot;]
        ///
        ///1.c4 Nf6 2.Nc3 (2.g3) 2...e6 (2...e5 3.Nf3) 3.Nf3 d5 4.d4 (4.cxd5
        ///exd5 5.d4 (5.e3 Bd6 $15 (5...c6 $6))) 4...Nbd7 5.Bg5 h6 (5...c6) (
        ///5...Bb4 6.cxd5 exd5 {{ Best move.}} 7.e3 {{ White has a slight advantage.
        ///}} (7.Qc2 h6 $14)) 1-0
        ///.
        /// </summary>
        internal static string PgnFormatterAllAccoutrements {
            get {
                return ResourceManager.GetString("PgnFormatterAllAccoutrements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]{0}[Site &quot;?&quot;]{0}[Date &quot;????.??.??&quot;]{0}[Round &quot;?&quot;]{0}[White &quot;?&quot;]{0}[Black &quot;?&quot;]{0}[Result &quot;*&quot;]{0}[SetUp &quot;1&quot;]{0}[FEN &quot;2bq1rk1/3p1npp/p1p3N1/1rbB1Pp1/1pQ5/P5N1/1PP3PP/R3R2K w - - 0 23&quot;]{0}{0}23.Bxf7+ *
        ///.
        /// </summary>
        internal static string PgnFormatterCaptureWithCheck {
            get {
                return ResourceManager.GetString("PgnFormatterCaptureWithCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1. c4 g6 2. Nc3 ( 2. d4 Bg7 3. Nc3 ) *
        ///.
        /// </summary>
        internal static string PgnFormatterd4Variation {
            get {
                return ResourceManager.GetString("PgnFormatterd4Variation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;Hallsberg opJ&quot;]
        ///[Site &quot;Hallsberg&quot;]
        ///[Date &quot;1975.??.??&quot;]
        ///[Round &quot;1&quot;]
        ///[White &quot;Aperia, T.&quot;]
        ///[Black &quot;Benjamin, Joel&quot;]
        ///[Result &quot;1/2-1/2&quot;]
        ///[WhiteElo &quot;&quot;]
        ///[BlackElo &quot;&quot;]
        ///[ECO &quot;B22&quot;]
        ///
        ///1.e4 c5 2.c3 d5 3.exd5 Qxd5 4.d4 cxd4 5.cxd4 Nf6 6.Nc3 Qd8 7.Nf3 Bg4 8.Qb3 Bxf3
        ///9.gxf3 Qb6 10.Qxb6 axb6 11.Bb5+ Kd8 12.Be3 Nbd7 13.Ke2 e6 14.Rhd1 Bd6 15.d5 e5
        ///16.Na4 Bc5 17.Nxc5 bxc5 18.a4 b6 19.b4 cxb4 20.Rab1 Nc5 21.Rxb4 Nfd7 22.d6 Kc8
        ///23.Rc1 Ra7 24.Bc6 Ra5 25.Kf1 Nd3  1/2-1/2.
        /// </summary>
        internal static string PgnFormatterLongMainLine {
            get {
                return ResourceManager.GetString("PgnFormatterLongMainLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 e5 2.Nc3 Nf6 3.Nf3 Nc6 (3...d6) *
        ///.
        /// </summary>
        internal static string PgnFormatterVariationDefende5 {
            get {
                return ResourceManager.GetString("PgnFormatterVariationDefende5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 e5 2.Nc3 Nf6 3.Nf3 Nc6 
        ///    ( 3...d6 )
        ///*
        ///.
        /// </summary>
        internal static string PgnFormatterVariationEnd {
            get {
                return ResourceManager.GetString("PgnFormatterVariationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]{0}[Site &quot;?&quot;]{0}[Date &quot;????.??.??&quot;]{0}[Round &quot;?&quot;]{0}[White &quot;?&quot;]{0}[Black &quot;?&quot;]{0}[Result &quot;*&quot;]{0}{0}1.c4 {0}    ( 1.d4 ){0}*{0}.
        /// </summary>
        internal static string PgnFormatterVariationInitial {
            get {
                return ResourceManager.GetString("PgnFormatterVariationInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot; White to move.&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;1998.??.??&quot;]
        ///[Round &quot;001&quot;]
        ///[White &quot;Chapter 1&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;1-0&quot;]
        ///[EventDate &quot;1998.??.??&quot;]
        ///[Annotator &quot;Magne,Alf&quot;]
        ///[PlyCount &quot;7&quot;]
        ///[SetUp &quot;1&quot;]
        ///[FEN &quot;r1b2rk1/pp1p1pp1/1b1p2B1/n1qQ2p1/8/5N2/P3RPPP/4R1K1 w - - 0 1&quot;]
        ///
        ///1.Qxf7+ 
        ///    ( 1.Bxf7+ Kh8 
        ///        ( 1...Kh7 2.Qd3+ Kh8 
        ///            ( 2...Qf5 3.Qxf5+ )
        ///        3.Qg6 )
        ///    2.Qd3 )
        ///1...Rxf7 2.Re8+ Rf8 3.Rxf8+ Kxf8 4.Re8# 1-0.
        /// </summary>
        internal static string Puzzle {
            get {
                return ResourceManager.GetString("Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 Nf6 2.d4 e6 3.Nf3 d5 *.
        /// </summary>
        internal static string s1 {
            get {
                return ResourceManager.GetString("s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 Nf6 2.d4 e6 .
        /// </summary>
        internal static string s2 {
            get {
                return ResourceManager.GetString("s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 Nf6 
        ///    ( 1...d5 )
        ///*.
        /// </summary>
        internal static string ShortVariation {
            get {
                return ResourceManager.GetString("ShortVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event &quot;?&quot;]
        ///[Site &quot;?&quot;]
        ///[Date &quot;????.??.??&quot;]
        ///[Round &quot;?&quot;]
        ///[White &quot;?&quot;]
        ///[Black &quot;?&quot;]
        ///[Result &quot;*&quot;]
        ///
        ///1.c4 Nf6 
        ///    ( 1...e5 )
        ///    ( 1...e6 )
        ///    ( 1...c5 )
        ///2.Nc3 *.
        /// </summary>
        internal static string WithVariations {
            get {
                return ResourceManager.GetString("WithVariations", resourceCulture);
            }
        }
    }
}
