//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\PGN.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ChessLib.Parse.PGN.Parser.BaseClasses {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class PGNLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		QUOTE=1, WHITE_WINS=2, BLACK_WINS=3, DRAWN_GAME=4, SECTION_MARKER=5, REST_OF_LINE_COMMENT=6, 
		BRACE_COMMENT=7, ESCAPE=8, SPACES=9, STRING=10, INTEGER=11, PERIOD=12, 
		TRIP_PERIOD=13, ASTERISK=14, LEFT_BRACKET=15, RIGHT_BRACKET=16, LEFT_PARENTHESIS=17, 
		RIGHT_PARENTHESIS=18, LEFT_ANGLE_BRACKET=19, RIGHT_ANGLE_BRACKET=20, NUMERIC_ANNOTATION_GLYPH=21, 
		SYMBOL=22, SUFFIX_ANNOTATION=23, UNEXPECTED_CHAR=24;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"QUOTE", "WHITE_WINS", "BLACK_WINS", "DRAWN_GAME", "SECTION_MARKER", "REST_OF_LINE_COMMENT", 
		"BRACE_COMMENT", "ESCAPE", "SPACES", "STRING", "INTEGER", "PERIOD", "TRIP_PERIOD", 
		"ASTERISK", "LEFT_BRACKET", "RIGHT_BRACKET", "LEFT_PARENTHESIS", "RIGHT_PARENTHESIS", 
		"LEFT_ANGLE_BRACKET", "RIGHT_ANGLE_BRACKET", "NUMERIC_ANNOTATION_GLYPH", 
		"SYMBOL", "SUFFIX_ANNOTATION", "UNEXPECTED_CHAR"
	};


	public PGNLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public PGNLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'\"'", "'1-0'", "'0-1'", "'1/2-1/2'", "'\r\n\r\n'", null, null, 
		null, null, null, null, "'.'", "'...'", "'*'", "'['", "']'", "'('", "')'", 
		"'<'", "'>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "QUOTE", "WHITE_WINS", "BLACK_WINS", "DRAWN_GAME", "SECTION_MARKER", 
		"REST_OF_LINE_COMMENT", "BRACE_COMMENT", "ESCAPE", "SPACES", "STRING", 
		"INTEGER", "PERIOD", "TRIP_PERIOD", "ASTERISK", "LEFT_BRACKET", "RIGHT_BRACKET", 
		"LEFT_PARENTHESIS", "RIGHT_PARENTHESIS", "LEFT_ANGLE_BRACKET", "RIGHT_ANGLE_BRACKET", 
		"NUMERIC_ANNOTATION_GLYPH", "SYMBOL", "SUFFIX_ANNOTATION", "UNEXPECTED_CHAR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PGN.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static PGNLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 7 : return ESCAPE_sempred(_localctx, predIndex);
		}
		return true;
	}
	private bool ESCAPE_sempred(RuleContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Column == 0;
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1A', '\xA8', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\a', '\a', 
		'O', '\n', '\a', '\f', '\a', '\xE', '\a', 'R', '\v', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\b', '\x3', '\b', '\a', '\b', 'X', '\n', '\b', '\f', 
		'\b', '\xE', '\b', '[', '\v', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\a', '\t', '\x62', '\n', '\t', '\f', '\t', 
		'\xE', '\t', '\x65', '\v', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', 
		'\x6', '\n', 'j', '\n', '\n', '\r', '\n', '\xE', '\n', 'k', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\a', '\v', 'v', '\n', '\v', '\f', '\v', '\xE', '\v', 
		'y', '\v', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x6', '\f', '~', 
		'\n', '\f', '\r', '\f', '\xE', '\f', '\x7F', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', 
		'\x6', '\x16', '\x98', '\n', '\x16', '\r', '\x16', '\xE', '\x16', '\x99', 
		'\x3', '\x17', '\x3', '\x17', '\a', '\x17', '\x9E', '\n', '\x17', '\f', 
		'\x17', '\xE', '\x17', '\xA1', '\v', '\x17', '\x3', '\x18', '\x3', '\x18', 
		'\x5', '\x18', '\xA5', '\n', '\x18', '\x3', '\x19', '\x3', '\x19', '\x2', 
		'\x2', '\x1A', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', 
		'\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', 
		'\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', 
		'!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', 
		'\x17', '-', '\x18', '/', '\x19', '\x31', '\x1A', '\x3', '\x2', '\n', 
		'\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x3', '\x2', '\x7F', '\x7F', 
		'\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x4', '\x2', '$', 
		'$', '^', '^', '\x3', '\x2', '\x32', ';', '\x5', '\x2', '\x32', ';', '\x43', 
		'\\', '\x63', '|', '\n', '\x2', '%', '%', '-', '-', '/', '/', '\x32', 
		'<', '?', '?', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x4', '\x2', 
		'#', '#', '\x41', '\x41', '\x2', '\xB2', '\x2', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '\x33', '\x3', '\x2', '\x2', '\x2', '\x5', '\x37', '\x3', 
		'\x2', '\x2', '\x2', '\a', ';', '\x3', '\x2', '\x2', '\x2', '\t', '?', 
		'\x3', '\x2', '\x2', '\x2', '\v', 'G', '\x3', '\x2', '\x2', '\x2', '\r', 
		'L', '\x3', '\x2', '\x2', '\x2', '\xF', 'U', '\x3', '\x2', '\x2', '\x2', 
		'\x11', '^', '\x3', '\x2', '\x2', '\x2', '\x13', 'i', '\x3', '\x2', '\x2', 
		'\x2', '\x15', 'o', '\x3', '\x2', '\x2', '\x2', '\x17', '}', '\x3', '\x2', 
		'\x2', '\x2', '\x19', '\x81', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x83', 
		'\x3', '\x2', '\x2', '\x2', '\x1D', '\x87', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', '\x89', '\x3', '\x2', '\x2', '\x2', '!', '\x8B', '\x3', '\x2', 
		'\x2', '\x2', '#', '\x8D', '\x3', '\x2', '\x2', '\x2', '%', '\x8F', '\x3', 
		'\x2', '\x2', '\x2', '\'', '\x91', '\x3', '\x2', '\x2', '\x2', ')', '\x93', 
		'\x3', '\x2', '\x2', '\x2', '+', '\x95', '\x3', '\x2', '\x2', '\x2', '-', 
		'\x9B', '\x3', '\x2', '\x2', '\x2', '/', '\xA2', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '\xA6', '\x3', '\x2', '\x2', '\x2', '\x33', '\x34', '\a', 
		'$', '\x2', '\x2', '\x34', '\x35', '\x3', '\x2', '\x2', '\x2', '\x35', 
		'\x36', '\b', '\x2', '\x2', '\x2', '\x36', '\x4', '\x3', '\x2', '\x2', 
		'\x2', '\x37', '\x38', '\a', '\x33', '\x2', '\x2', '\x38', '\x39', '\a', 
		'/', '\x2', '\x2', '\x39', ':', '\a', '\x32', '\x2', '\x2', ':', '\x6', 
		'\x3', '\x2', '\x2', '\x2', ';', '<', '\a', '\x32', '\x2', '\x2', '<', 
		'=', '\a', '/', '\x2', '\x2', '=', '>', '\a', '\x33', '\x2', '\x2', '>', 
		'\b', '\x3', '\x2', '\x2', '\x2', '?', '@', '\a', '\x33', '\x2', '\x2', 
		'@', '\x41', '\a', '\x31', '\x2', '\x2', '\x41', '\x42', '\a', '\x34', 
		'\x2', '\x2', '\x42', '\x43', '\a', '/', '\x2', '\x2', '\x43', '\x44', 
		'\a', '\x33', '\x2', '\x2', '\x44', '\x45', '\a', '\x31', '\x2', '\x2', 
		'\x45', '\x46', '\a', '\x34', '\x2', '\x2', '\x46', '\n', '\x3', '\x2', 
		'\x2', '\x2', 'G', 'H', '\a', '\xF', '\x2', '\x2', 'H', 'I', '\a', '\f', 
		'\x2', '\x2', 'I', 'J', '\a', '\xF', '\x2', '\x2', 'J', 'K', '\a', '\f', 
		'\x2', '\x2', 'K', '\f', '\x3', '\x2', '\x2', '\x2', 'L', 'P', '\a', '=', 
		'\x2', '\x2', 'M', 'O', '\n', '\x2', '\x2', '\x2', 'N', 'M', '\x3', '\x2', 
		'\x2', '\x2', 'O', 'R', '\x3', '\x2', '\x2', '\x2', 'P', 'N', '\x3', '\x2', 
		'\x2', '\x2', 'P', 'Q', '\x3', '\x2', '\x2', '\x2', 'Q', 'S', '\x3', '\x2', 
		'\x2', '\x2', 'R', 'P', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\b', '\a', 
		'\x2', '\x2', 'T', '\xE', '\x3', '\x2', '\x2', '\x2', 'U', 'Y', '\a', 
		'}', '\x2', '\x2', 'V', 'X', '\n', '\x3', '\x2', '\x2', 'W', 'V', '\x3', 
		'\x2', '\x2', '\x2', 'X', '[', '\x3', '\x2', '\x2', '\x2', 'Y', 'W', '\x3', 
		'\x2', '\x2', '\x2', 'Y', 'Z', '\x3', '\x2', '\x2', '\x2', 'Z', '\\', 
		'\x3', '\x2', '\x2', '\x2', '[', 'Y', '\x3', '\x2', '\x2', '\x2', '\\', 
		']', '\a', '\x7F', '\x2', '\x2', ']', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'^', '_', '\x6', '\t', '\x2', '\x2', '_', '\x63', '\a', '\'', '\x2', '\x2', 
		'`', '\x62', '\n', '\x2', '\x2', '\x2', '\x61', '`', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '\x65', '\x3', '\x2', '\x2', '\x2', '\x63', '\x61', '\x3', 
		'\x2', '\x2', '\x2', '\x63', '\x64', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'\x66', '\x3', '\x2', '\x2', '\x2', '\x65', '\x63', '\x3', '\x2', '\x2', 
		'\x2', '\x66', 'g', '\b', '\t', '\x2', '\x2', 'g', '\x12', '\x3', '\x2', 
		'\x2', '\x2', 'h', 'j', '\t', '\x4', '\x2', '\x2', 'i', 'h', '\x3', '\x2', 
		'\x2', '\x2', 'j', 'k', '\x3', '\x2', '\x2', '\x2', 'k', 'i', '\x3', '\x2', 
		'\x2', '\x2', 'k', 'l', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\x3', '\x2', 
		'\x2', '\x2', 'm', 'n', '\b', '\n', '\x2', '\x2', 'n', '\x14', '\x3', 
		'\x2', '\x2', '\x2', 'o', 'w', '\a', '$', '\x2', '\x2', 'p', 'q', '\a', 
		'^', '\x2', '\x2', 'q', 'v', '\a', '^', '\x2', '\x2', 'r', 's', '\a', 
		'^', '\x2', '\x2', 's', 'v', '\a', '$', '\x2', '\x2', 't', 'v', '\n', 
		'\x5', '\x2', '\x2', 'u', 'p', '\x3', '\x2', '\x2', '\x2', 'u', 'r', '\x3', 
		'\x2', '\x2', '\x2', 'u', 't', '\x3', '\x2', '\x2', '\x2', 'v', 'y', '\x3', 
		'\x2', '\x2', '\x2', 'w', 'u', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\x3', 
		'\x2', '\x2', '\x2', 'x', 'z', '\x3', '\x2', '\x2', '\x2', 'y', 'w', '\x3', 
		'\x2', '\x2', '\x2', 'z', '{', '\a', '$', '\x2', '\x2', '{', '\x16', '\x3', 
		'\x2', '\x2', '\x2', '|', '~', '\t', '\x6', '\x2', '\x2', '}', '|', '\x3', 
		'\x2', '\x2', '\x2', '~', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x7F', 
		'}', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '\x80', '\x18', '\x3', '\x2', '\x2', '\x2', '\x81', '\x82', '\a', 
		'\x30', '\x2', '\x2', '\x82', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x83', 
		'\x84', '\a', '\x30', '\x2', '\x2', '\x84', '\x85', '\a', '\x30', '\x2', 
		'\x2', '\x85', '\x86', '\a', '\x30', '\x2', '\x2', '\x86', '\x1C', '\x3', 
		'\x2', '\x2', '\x2', '\x87', '\x88', '\a', ',', '\x2', '\x2', '\x88', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\a', ']', '\x2', 
		'\x2', '\x8A', ' ', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\a', 
		'_', '\x2', '\x2', '\x8C', '\"', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8E', 
		'\a', '*', '\x2', '\x2', '\x8E', '$', '\x3', '\x2', '\x2', '\x2', '\x8F', 
		'\x90', '\a', '+', '\x2', '\x2', '\x90', '&', '\x3', '\x2', '\x2', '\x2', 
		'\x91', '\x92', '\a', '>', '\x2', '\x2', '\x92', '(', '\x3', '\x2', '\x2', 
		'\x2', '\x93', '\x94', '\a', '@', '\x2', '\x2', '\x94', '*', '\x3', '\x2', 
		'\x2', '\x2', '\x95', '\x97', '\a', '&', '\x2', '\x2', '\x96', '\x98', 
		'\t', '\x6', '\x2', '\x2', '\x97', '\x96', '\x3', '\x2', '\x2', '\x2', 
		'\x98', '\x99', '\x3', '\x2', '\x2', '\x2', '\x99', '\x97', '\x3', '\x2', 
		'\x2', '\x2', '\x99', '\x9A', '\x3', '\x2', '\x2', '\x2', '\x9A', ',', 
		'\x3', '\x2', '\x2', '\x2', '\x9B', '\x9F', '\t', '\a', '\x2', '\x2', 
		'\x9C', '\x9E', '\t', '\b', '\x2', '\x2', '\x9D', '\x9C', '\x3', '\x2', 
		'\x2', '\x2', '\x9E', '\xA1', '\x3', '\x2', '\x2', '\x2', '\x9F', '\x9D', 
		'\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\x3', '\x2', '\x2', '\x2', 
		'\xA0', '.', '\x3', '\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', '\x2', 
		'\x2', '\x2', '\xA2', '\xA4', '\t', '\t', '\x2', '\x2', '\xA3', '\xA5', 
		'\t', '\t', '\x2', '\x2', '\xA4', '\xA3', '\x3', '\x2', '\x2', '\x2', 
		'\xA4', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA5', '\x30', '\x3', '\x2', 
		'\x2', '\x2', '\xA6', '\xA7', '\v', '\x2', '\x2', '\x2', '\xA7', '\x32', 
		'\x3', '\x2', '\x2', '\x2', '\r', '\x2', 'P', 'Y', '\x63', 'k', 'u', 'w', 
		'\x7F', '\x99', '\x9F', '\xA4', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace ChessLib.Parse.PGN.Parser.BaseClasses
