//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\PGN.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ChessLib.Parse.PGN.Parser.BaseClasses {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class PGNLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		WHITE_WINS=1, BLACK_WINS=2, DRAWN_GAME=3, SECTION_MARKER=4, REST_OF_LINE_COMMENT=5, 
		BRACE_COMMENT=6, ESCAPE=7, SPACES=8, STRING=9, INTEGER=10, PERIOD=11, 
		TRIP_PERIOD=12, ASTERISK=13, LEFT_BRACKET=14, RIGHT_BRACKET=15, LEFT_PARENTHESIS=16, 
		RIGHT_PARENTHESIS=17, LEFT_ANGLE_BRACKET=18, RIGHT_ANGLE_BRACKET=19, NUMERIC_ANNOTATION_GLYPH=20, 
		SYMBOL=21, SUFFIX_ANNOTATION=22, UNEXPECTED_CHAR=23;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"WHITE_WINS", "BLACK_WINS", "DRAWN_GAME", "SECTION_MARKER", "REST_OF_LINE_COMMENT", 
		"BRACE_COMMENT", "ESCAPE", "SPACES", "STRING", "INTEGER", "PERIOD", "TRIP_PERIOD", 
		"ASTERISK", "LEFT_BRACKET", "RIGHT_BRACKET", "LEFT_PARENTHESIS", "RIGHT_PARENTHESIS", 
		"LEFT_ANGLE_BRACKET", "RIGHT_ANGLE_BRACKET", "NUMERIC_ANNOTATION_GLYPH", 
		"SYMBOL", "SUFFIX_ANNOTATION", "UNEXPECTED_CHAR"
	};


	public PGNLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public PGNLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'1-0'", "'0-1'", "'1/2-1/2'", "'\r\n\r\n'", null, null, null, null, 
		null, null, "'.'", "'...'", "'*'", "'['", "']'", "'('", "')'", "'<'", 
		"'>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "WHITE_WINS", "BLACK_WINS", "DRAWN_GAME", "SECTION_MARKER", "REST_OF_LINE_COMMENT", 
		"BRACE_COMMENT", "ESCAPE", "SPACES", "STRING", "INTEGER", "PERIOD", "TRIP_PERIOD", 
		"ASTERISK", "LEFT_BRACKET", "RIGHT_BRACKET", "LEFT_PARENTHESIS", "RIGHT_PARENTHESIS", 
		"LEFT_ANGLE_BRACKET", "RIGHT_ANGLE_BRACKET", "NUMERIC_ANNOTATION_GLYPH", 
		"SYMBOL", "SUFFIX_ANNOTATION", "UNEXPECTED_CHAR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PGN.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static PGNLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 6 : return ESCAPE_sempred(_localctx, predIndex);
		}
		return true;
	}
	private bool ESCAPE_sempred(RuleContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Column == 0;
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x19', '\xA2', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', 'I', '\n', 
		'\x6', '\f', '\x6', '\xE', '\x6', 'L', '\v', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\a', '\a', 'R', '\n', '\a', '\f', '\a', 
		'\xE', '\a', 'U', '\v', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\a', '\b', '\\', '\n', '\b', '\f', '\b', '\xE', '\b', 
		'_', '\v', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x6', '\t', '\x64', 
		'\n', '\t', '\r', '\t', '\xE', '\t', '\x65', '\x3', '\t', '\x3', '\t', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\a', '\n', 'p', '\n', '\n', '\f', '\n', '\xE', '\n', 's', '\v', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x6', '\v', 'x', '\n', '\v', 
		'\r', '\v', '\xE', '\v', 'y', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x6', '\x15', '\x92', '\n', 
		'\x15', '\r', '\x15', '\xE', '\x15', '\x93', '\x3', '\x16', '\x3', '\x16', 
		'\a', '\x16', '\x98', '\n', '\x16', '\f', '\x16', '\xE', '\x16', '\x9B', 
		'\v', '\x16', '\x3', '\x17', '\x3', '\x17', '\x5', '\x17', '\x9F', '\n', 
		'\x17', '\x3', '\x18', '\x3', '\x18', '\x2', '\x2', '\x19', '\x3', '\x3', 
		'\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', 
		'\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', 
		'\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', 
		'/', '\x19', '\x3', '\x2', '\n', '\x4', '\x2', '\f', '\f', '\xF', '\xF', 
		'\x3', '\x2', '\x7F', '\x7F', '\x5', '\x2', '\v', '\f', '\xF', '\xF', 
		'\"', '\"', '\x4', '\x2', '$', '$', '^', '^', '\x3', '\x2', '\x32', ';', 
		'\x5', '\x2', '\x32', ';', '\x43', '\\', '\x63', '|', '\n', '\x2', '%', 
		'%', '-', '-', '/', '/', '\x32', '<', '?', '?', '\x43', '\\', '\x61', 
		'\x61', '\x63', '|', '\x4', '\x2', '#', '#', '\x41', '\x41', '\x2', '\xAC', 
		'\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '\x31', '\x3', '\x2', '\x2', '\x2', '\x5', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\a', '\x39', '\x3', '\x2', '\x2', '\x2', '\t', '\x41', 
		'\x3', '\x2', '\x2', '\x2', '\v', '\x46', '\x3', '\x2', '\x2', '\x2', 
		'\r', 'O', '\x3', '\x2', '\x2', '\x2', '\xF', 'X', '\x3', '\x2', '\x2', 
		'\x2', '\x11', '\x63', '\x3', '\x2', '\x2', '\x2', '\x13', 'i', '\x3', 
		'\x2', '\x2', '\x2', '\x15', 'w', '\x3', '\x2', '\x2', '\x2', '\x17', 
		'{', '\x3', '\x2', '\x2', '\x2', '\x19', '}', '\x3', '\x2', '\x2', '\x2', 
		'\x1B', '\x81', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x83', '\x3', '\x2', 
		'\x2', '\x2', '\x1F', '\x85', '\x3', '\x2', '\x2', '\x2', '!', '\x87', 
		'\x3', '\x2', '\x2', '\x2', '#', '\x89', '\x3', '\x2', '\x2', '\x2', '%', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\'', '\x8D', '\x3', '\x2', '\x2', 
		'\x2', ')', '\x8F', '\x3', '\x2', '\x2', '\x2', '+', '\x95', '\x3', '\x2', 
		'\x2', '\x2', '-', '\x9C', '\x3', '\x2', '\x2', '\x2', '/', '\xA0', '\x3', 
		'\x2', '\x2', '\x2', '\x31', '\x32', '\a', '\x33', '\x2', '\x2', '\x32', 
		'\x33', '\a', '/', '\x2', '\x2', '\x33', '\x34', '\a', '\x32', '\x2', 
		'\x2', '\x34', '\x4', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', 
		'\x32', '\x2', '\x2', '\x36', '\x37', '\a', '/', '\x2', '\x2', '\x37', 
		'\x38', '\a', '\x33', '\x2', '\x2', '\x38', '\x6', '\x3', '\x2', '\x2', 
		'\x2', '\x39', ':', '\a', '\x33', '\x2', '\x2', ':', ';', '\a', '\x31', 
		'\x2', '\x2', ';', '<', '\a', '\x34', '\x2', '\x2', '<', '=', '\a', '/', 
		'\x2', '\x2', '=', '>', '\a', '\x33', '\x2', '\x2', '>', '?', '\a', '\x31', 
		'\x2', '\x2', '?', '@', '\a', '\x34', '\x2', '\x2', '@', '\b', '\x3', 
		'\x2', '\x2', '\x2', '\x41', '\x42', '\a', '\xF', '\x2', '\x2', '\x42', 
		'\x43', '\a', '\f', '\x2', '\x2', '\x43', '\x44', '\a', '\xF', '\x2', 
		'\x2', '\x44', '\x45', '\a', '\f', '\x2', '\x2', '\x45', '\n', '\x3', 
		'\x2', '\x2', '\x2', '\x46', 'J', '\a', '=', '\x2', '\x2', 'G', 'I', '\n', 
		'\x2', '\x2', '\x2', 'H', 'G', '\x3', '\x2', '\x2', '\x2', 'I', 'L', '\x3', 
		'\x2', '\x2', '\x2', 'J', 'H', '\x3', '\x2', '\x2', '\x2', 'J', 'K', '\x3', 
		'\x2', '\x2', '\x2', 'K', 'M', '\x3', '\x2', '\x2', '\x2', 'L', 'J', '\x3', 
		'\x2', '\x2', '\x2', 'M', 'N', '\b', '\x6', '\x2', '\x2', 'N', '\f', '\x3', 
		'\x2', '\x2', '\x2', 'O', 'S', '\a', '}', '\x2', '\x2', 'P', 'R', '\n', 
		'\x3', '\x2', '\x2', 'Q', 'P', '\x3', '\x2', '\x2', '\x2', 'R', 'U', '\x3', 
		'\x2', '\x2', '\x2', 'S', 'Q', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\x3', 
		'\x2', '\x2', '\x2', 'T', 'V', '\x3', '\x2', '\x2', '\x2', 'U', 'S', '\x3', 
		'\x2', '\x2', '\x2', 'V', 'W', '\a', '\x7F', '\x2', '\x2', 'W', '\xE', 
		'\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\x6', '\b', '\x2', '\x2', 'Y', 
		']', '\a', '\'', '\x2', '\x2', 'Z', '\\', '\n', '\x2', '\x2', '\x2', '[', 
		'Z', '\x3', '\x2', '\x2', '\x2', '\\', '_', '\x3', '\x2', '\x2', '\x2', 
		']', '[', '\x3', '\x2', '\x2', '\x2', ']', '^', '\x3', '\x2', '\x2', '\x2', 
		'^', '`', '\x3', '\x2', '\x2', '\x2', '_', ']', '\x3', '\x2', '\x2', '\x2', 
		'`', '\x61', '\b', '\b', '\x2', '\x2', '\x61', '\x10', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '\x64', '\t', '\x4', '\x2', '\x2', '\x63', '\x62', '\x3', 
		'\x2', '\x2', '\x2', '\x64', '\x65', '\x3', '\x2', '\x2', '\x2', '\x65', 
		'\x63', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\x3', '\x2', '\x2', 
		'\x2', '\x66', 'g', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\b', '\t', 
		'\x2', '\x2', 'h', '\x12', '\x3', '\x2', '\x2', '\x2', 'i', 'q', '\a', 
		'$', '\x2', '\x2', 'j', 'k', '\a', '^', '\x2', '\x2', 'k', 'p', '\a', 
		'^', '\x2', '\x2', 'l', 'm', '\a', '^', '\x2', '\x2', 'm', 'p', '\a', 
		'$', '\x2', '\x2', 'n', 'p', '\n', '\x5', '\x2', '\x2', 'o', 'j', '\x3', 
		'\x2', '\x2', '\x2', 'o', 'l', '\x3', '\x2', '\x2', '\x2', 'o', 'n', '\x3', 
		'\x2', '\x2', '\x2', 'p', 's', '\x3', '\x2', '\x2', '\x2', 'q', 'o', '\x3', 
		'\x2', '\x2', '\x2', 'q', 'r', '\x3', '\x2', '\x2', '\x2', 'r', 't', '\x3', 
		'\x2', '\x2', '\x2', 's', 'q', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\a', 
		'$', '\x2', '\x2', 'u', '\x14', '\x3', '\x2', '\x2', '\x2', 'v', 'x', 
		'\t', '\x6', '\x2', '\x2', 'w', 'v', '\x3', '\x2', '\x2', '\x2', 'x', 
		'y', '\x3', '\x2', '\x2', '\x2', 'y', 'w', '\x3', '\x2', '\x2', '\x2', 
		'y', 'z', '\x3', '\x2', '\x2', '\x2', 'z', '\x16', '\x3', '\x2', '\x2', 
		'\x2', '{', '|', '\a', '\x30', '\x2', '\x2', '|', '\x18', '\x3', '\x2', 
		'\x2', '\x2', '}', '~', '\a', '\x30', '\x2', '\x2', '~', '\x7F', '\a', 
		'\x30', '\x2', '\x2', '\x7F', '\x80', '\a', '\x30', '\x2', '\x2', '\x80', 
		'\x1A', '\x3', '\x2', '\x2', '\x2', '\x81', '\x82', '\a', ',', '\x2', 
		'\x2', '\x82', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', '\a', 
		']', '\x2', '\x2', '\x84', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x85', 
		'\x86', '\a', '_', '\x2', '\x2', '\x86', ' ', '\x3', '\x2', '\x2', '\x2', 
		'\x87', '\x88', '\a', '*', '\x2', '\x2', '\x88', '\"', '\x3', '\x2', '\x2', 
		'\x2', '\x89', '\x8A', '\a', '+', '\x2', '\x2', '\x8A', '$', '\x3', '\x2', 
		'\x2', '\x2', '\x8B', '\x8C', '\a', '>', '\x2', '\x2', '\x8C', '&', '\x3', 
		'\x2', '\x2', '\x2', '\x8D', '\x8E', '\a', '@', '\x2', '\x2', '\x8E', 
		'(', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x91', '\a', '&', '\x2', '\x2', 
		'\x90', '\x92', '\t', '\x6', '\x2', '\x2', '\x91', '\x90', '\x3', '\x2', 
		'\x2', '\x2', '\x92', '\x93', '\x3', '\x2', '\x2', '\x2', '\x93', '\x91', 
		'\x3', '\x2', '\x2', '\x2', '\x93', '\x94', '\x3', '\x2', '\x2', '\x2', 
		'\x94', '*', '\x3', '\x2', '\x2', '\x2', '\x95', '\x99', '\t', '\a', '\x2', 
		'\x2', '\x96', '\x98', '\t', '\b', '\x2', '\x2', '\x97', '\x96', '\x3', 
		'\x2', '\x2', '\x2', '\x98', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x99', 
		'\x97', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\x3', '\x2', '\x2', 
		'\x2', '\x9A', ',', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x99', '\x3', 
		'\x2', '\x2', '\x2', '\x9C', '\x9E', '\t', '\t', '\x2', '\x2', '\x9D', 
		'\x9F', '\t', '\t', '\x2', '\x2', '\x9E', '\x9D', '\x3', '\x2', '\x2', 
		'\x2', '\x9E', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x9F', '.', '\x3', 
		'\x2', '\x2', '\x2', '\xA0', '\xA1', '\v', '\x2', '\x2', '\x2', '\xA1', 
		'\x30', '\x3', '\x2', '\x2', '\x2', '\r', '\x2', 'J', 'S', ']', '\x65', 
		'o', 'q', 'y', '\x93', '\x99', '\x9E', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace ChessLib.Parse.PGN.Parser.BaseClasses
